### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by nongdenchet** [nongdenchet/coder_ticket#1]
Here is my assignment 3 /cc @coderschoolreview

**Comment by harley** [comment]
Hi @nongdenchet, congrats for winning the homework prize with 100% test coverage and highest code quality this week. I'm very impressed and it's a great pleasure to browse through the components 🙇 

Goals of this homework:
- To get a good feel of testing in general for a Rails app by both adding features and adding tests for them. Sometimes you test first; sometimes you add functionalities first. Think about your programming style: what approach will save you time now AND later. Be willing to change your habit.
- To appreciate test coverage in general and the code coverage analysis in particular with SimpleCov, which is on top of [Ruby's built-in coverage](http://www.ruby-doc.org/stdlib-2.1.0/libdoc/coverage/rdoc/Coverage.html) library but is much easier to use.
- To understand that model tests are the easiest to write and the most useful. Do this as much as you can.

Some comments
- Re: your question under `Issue`, "Dont know how to retrieve carrierwave image for edit form", how about putting `<%= image_tag(@event.local_image.url(:thumb)) if @event.local_image? %>` in your even form?
- Add `rspec-rails` to both the `:development` and `:test` groups because you want rspec generators in development.
- Good to see the `test` folder removed to make it clear you are using `spec` only. When generating a new rails project, you can generate `rails new appname --database=postgresql -T` and you will see that it explicitly not include `rails/test_unit`
- In config/routes, you use `resource :sessions` -- technically it should be `resource :session` (and you know it still refers to SessionsController). in general, try to do "resources". [Singular resources](http://guides.rubyonrails.org/routing.html#singular-resources) is not worth it. Good job limiting your routes with `:except` and `:only` to clearly indicate what you need.
- In Category model, put a list of category names in a constant. For more important projects, you may want to use enum type which allows for handling multiple languages more easily.
- Good use of decorators, services and tests for them. On a scale of 1-5 how useful do you think they are for your projects in general? Should they be added at the start or should they be added later to a well tested code base.
- For file uploads, are you uploading to temp folders on heroku and accept the [epheral filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) set up for now? Have you considered using filestack or AWS S3 for the final project?
- What do you need mini_magick for? I don't see any resizing or other image manipulation.

Tests:
- Awesome that you use `describe "#instance_method"`, `describe ".class_method"` and `context "other grouping/scenarios"`
- You may want to take advantage of `let` to reduce the code in the `before` block. See [let and let!](https://relishapp.com/rspec/rspec-core/docs/helper-methods/let-and-let)
- Good job with using FactoryGirl for your convenience. I don't recommend using too many libraries for people who are new to testing, but you are obviously comfortable with it.
- I don't think you need the `database_cleaner` gem here because you don't use integration tests here. Do you?

Sorry for the slow review. Good luck with the final project and I look forward to answering any questions from you and others.

**Comment by nongdenchet** [comment]
"Good use of decorators, services and tests for them. On a scale of 1-5 how useful do you think they are for your projects in general? Should they be added at the start or should they be added later to a well tested code base.". I think I would give 5, it is really useful for me, to stick with One-Responsibility rule. I think would love to add them from the start. Or sometime when the legacy controller (well tested) be come fat I will extract the service, and make sure the test still passed. @harley
